# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ace-drawing-demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ace-drawing-demo
	pod 'ACEDrawingView'

  target 'ace-drawing-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ace-drawing-demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
